# -*- coding: utf-8 -*-
"""Shilviana M A_Tugas_Prak_Fiskom3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ioyYK84v-eNEMcBPC9smO5a99p6AYXVu
"""

import pandas as pd

last_names = ['Connor', 'Connor', 'Reese']
first_names = ['Sarah', 'John', 'Kyle']
df = pd.DataFrame({
  'first_name': first_names,
  'last_name': last_names,
})

url = "https://github.com/luminati-io/Instagram-dataset-samples/raw/main/Instagram%20Profiles%20-%20Github%20Hashtag.xlsx"
database = pd.read_excel(url)
'''pd.read_csv('data.csv')'''
print(database.columns)
print(database.describe())
print(database.head())
print(database.tail())

import numpy as np
x = [i for i in range(0,5)]
y = np.sin(x)

print(x,y)

dataframe = pd.DataFrame({
    'x': x,
    'y': y
                             })
dataframe['z'] = np.cos(x)

dataframe